# Auto-label PRs based on changed files
"area: core":
  - any: ["Dockerfile", "requirements.txt"]

"area: tests":
  - any: ["tests/**"]

"area: docs":
  - any: ["*.md", "docs/**"]

"area: ci/cd":
  - any: [".github/**"]
